ScholarshipApp/Models/Application/ApplicationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ScholarshipApp.Models.Application
{
    public class ApplicationViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Birthdate")]
        public DateTime BirthDate { get; set; }

        [Required]
        [Display(Name = "National Id")]
        public Int64 NationalId { get; set; }

        [Required]
        [Display(Name = "University")]
        public string University { get; set; }

        [Required]
        [Display(Name = "Major")]
        public string Major { get; set; }

        [Required]
        [Display(Name = "GPA")]
        public float GPA { get; set; }


        //[Required]
        //[FileExtensions(Extensions = "pdf", ErrorMessage = "Only files with pdf extensions are allowed.")]
        public HttpPostedFileBase Resume { get; set; }
    }
}

ScholarshipApp/Controllers/ApplicationController.cs
using ScholarshipApp.DataAccess;
using ScholarshipApp.Models.Application;
using ScholarshipApp.Repository;
using ScholarshipApp.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace ScholarshipApp.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly FileUtility _fileUtility;
        private readonly UserRepository _userRepository;
        private readonly ApplicationRepository _applicationRepository;

        public ApplicationController()
        {
            _fileUtility = new FileUtility();
            _userRepository = new UserRepository();
            _applicationRepository = new ApplicationRepository();
        }

        [HttpGet]
        public ActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Apply(ApplicationViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Save PDF File
                string resumeFileName = _fileUtility.SaveResume(model.Resume);

                // Add User
                User user = new User {
                    Email = model.Email,
                    Password = model.Password,
                    Role = "student"
                };

                int? userId = _userRepository.AddStudent(user);

                if(userId != null)
                {
                    DataAccess.Application applicationModel = new DataAccess.Application
                    {
                        UserId = (int)userId,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        BirthDate = model.BirthDate.ToShortDateString(),
                        NationalId = model.NationalId,
                        University = model.University,
                        Major = model.Major,
                        GPA = model.GPA,
                        ResumeFileName = resumeFileName,
                        IsAccepted = null
                    };

                    int? applicationId = _applicationRepository.AddApplication(applicationModel);

                    if(applicationId != null)
                    {
                        // Do something when submitted
                        TempData["SubmitSuccess"] = "True";
                        return RedirectToAction("Index", "Home");
                    }

                }
            }

            TempData["SubmitError"] = "True";
            return View();
        }

        public ActionResult Edit(int id)
        {
            var userApplication = _applicationRepository.GetApplication(id);
            if(userApplication != null)
            {
                ApplicationViewModel model = new ApplicationViewModel()
                {                    
                    Email = TempData["Email"].ToString(),
                    Password = TempData["Password"].ToString(),
                    FirstName = userApplication.FirstName,
                    LastName = userApplication.LastName,
                    BirthDate = Convert.ToDateTime(userApplication.BirthDate).Date,
                    NationalId = userApplication.NationalId,
                    University= userApplication.University,
                    Major = userApplication.Major,
                    GPA = userApplication.GPA
                };

                TempData["ApplicationId_TobeEdited"] = userApplication.Id;
                return View(model);
            }
            else
            {
                TempData["StudentGetApplicationError"] = "True";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(ApplicationViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Save PDF File
                
                string resumeFileName = model.Resume == null? null: _fileUtility.SaveResume(model.Resume);
                
                if (TempData["ApplicationId_TobeEdited"] != null)
                {
                    int? applicationId = _applicationRepository.EditApplication(model, (int)TempData["ApplicationId_TobeEdited"], resumeFileName);

                    if (applicationId != null)
                    {
                        TempData["EditSuccess"] = "True";
                        return RedirectToAction("Index", "Home");
                    }

                }
            }

            TempData["SubmitError"] = "True";
            return View();

        }
    }
}

ScholarshipApp/Views/Application/Apply.cshtml
@model ScholarshipApp.Models.Application.ApplicationViewModel

@{
    ViewBag.Title = "AddApplication";
}

<div class="jumbotron">
        @{ 
            if(TempData["SubmitError"] != null && TempData["SubmitError"].ToString() == "True")
            {
            <div class="alert alert-danger" role="alert">
                Faied to submit your application, try again
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            }
        }
    <h2 class="text-center">Application Submit</h2>
    <p class="lead">Please, fill all the following fields.</p>

    @using (Html.BeginForm("Apply", "Application", FormMethod.Post, new { @id = "applyFormId", @class = "form-horizontal", role = "form" , enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        HtmlHelper.UnobtrusiveJavaScriptEnabled = true;

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger " })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.BirthDate, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.BirthDate, new { @class = "form-control"})
                @Html.ValidationMessageFor(m => m.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.NationalId, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.NationalId, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.NationalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.University, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.University, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.University, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.Major, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Major, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Major, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.GPA, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.GPA, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.GPA, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.Resume, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Resume, new { type = "file", @class = "input-file" })
                @Html.ValidationMessageFor(m => m.Resume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" />
                <button type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Index", "Home")'">Cancel</button>
            </div>
        </div>


    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @*@Scripts.Render("~/bundles/custom-validator")*@
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
}

<script type="text/javascript">

    $(document).ready(function () {
        $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
        });

    });
</script>

ScholarshipApp/Views/Application/Edit.cshtml
@model ScholarshipApp.Models.Application.ApplicationViewModel
@{
    ViewBag.Title = "Edit Application";
}



<div class="jumbotron">

    <h2 class="text-center">Application Edit</h2>
    <p class="lead">Please, fill all the following fields.</p>

    @using (Html.BeginForm("Edit", "Application", FormMethod.Post, new { @id = "editFormId", @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        HtmlHelper.UnobtrusiveJavaScriptEnabled = true;

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" , @value = Model.Password})
                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger " })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.BirthDate, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.BirthDate, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.NationalId, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.NationalId, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.NationalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.University, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.University, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.University, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.Major, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Major, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Major, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.GPA, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.GPA, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.GPA, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(m => m.Resume, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Resume, new { type = "file", @class = "input-file" })
                @Html.ValidationMessageFor(m => m.Resume, "", new { @class = "text-danger" })
                <small id="fileHelp" class="form-text text-muted">Upload new resume or leave empty.</small>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary btn-lg" value="Edit" />
                <button type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Index", "Home")'">Cancel</button>
            </div>
        </div>


    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @*@Scripts.Render("~/bundles/custom-validator")*@
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
}

<script type="text/javascript">

    $(document).ready(function () {
        $('input[type=datetime]').datepicker({
            dateFormat: "dd/M/yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-60:+0"
        });

        //$('.datepicker').datepicker(); //Initialise any date pickers
    });
</script>